#! /usr/bin/env Rscript
args=(commandArgs(TRUE))
sex <- as.numeric(args[1])
age <- as.numeric(args[2])
avg_income <- as.numeric(args[3])
avg_spend <- as.numeric(args[4])
avg_debt <- as.numeric(args[5])
avg_debt_credit <- as.numeric(args[6])
vehicle_own_rat <- as.numeric(args[7])
CSV <- read.csv(file="/home/FP/test/jeju.csv")
CSV <- read.csv(file="/home/FP/test/jeju.csv")
modeling <- lm(avg_credit_rat ~., data = CSV)
target5 <- data.frame(sex=sex, age=age, avg_income=avg_income, avg_spend=avg_spend, avg_debt=avg_debt, avg_debt_credit=avg_debt_credit, vehicle_own_rat=vehicle_own_rat)
predict(modeling, newdata=target5)
